# Generated by Django 5.2.16 on 2026-07-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_pet_embedding_pet_sex_alter_pet_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='location',
            field=models.CharField(default='unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('lost', 'Lost'), ('stray', 'Stray'), ('fostered', 'Fostered'), ('reunited', 'Reunited'), ('adopted', 'Adopted'), ('claimed', 'Claimed')], max_length=100),
        ),
    ]
