# Generated by Django 5.2.16 on 2026-09-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_pet_location_alter_pet_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='description',
            new_name='message',
        ),
        migrations.AlterField(
            model_name='pet',
            name='location',
            field=models.CharField(blank=True, default='unknown', max_length=200, null=True),
        ),
    ]
